# Generated by Django 3.0.7 on 2020-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200615_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(verbose_name='Atalho'),
        ),
    ]
