# Generated by Django 3.0.8 on 2020-08-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_replay_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Identificador'),
        ),
    ]
