# Generated by Django 3.0.8 on 2020-08-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Identificador'),
        ),
    ]
