# Generated by Django 3.0.8 on 2020-08-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200818_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Identificador'),
        ),
    ]
