# Generated by Django 3.0.8 on 2020-08-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20200818_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Identificador'),
        ),
    ]
