# Generated by Django 3.0.7 on 2020-07-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emil',
            new_name='email',
        ),
    ]
